---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1803781/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R vendor  $DEPLOYPATH
    - /bin/cp -R writable  $DEPLOYPATH
    - /bin/cp index.php  $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    